name: Create build on tag

env:
  NPM_TOKEN: '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'
  AWS_DEFAULT_REGION: 'us-east-1'

on:
  push:
    tags:
      - 'v*'

jobs:
  build-sync-s3:
    name: Push the build to S3