name: Semantic Release

on:
  push:
    branches:
      - main
      - dev
      - master
      - 'release/**'

jobs:
  semanticReleaseJob:
    if: "!startsWith(github.event.commits[0].message, 'chore')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: semanticReleaseStep
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GITHUB_TOKEN: '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'
          NPM_TOKEN: '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'
        run: |
          echo "//npm.pkg.github.com/:_authToken=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" > .npmrc
          echo "@tenna-llc:registry=https://npm.pkg.github.com/" >> .npmrc
          npm install -g https://github.com/tenna-llc/semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm -D --force
          npx semantic-release
